require:
  - rubocop-rails
  
AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'lib/**/*'
    - 'script/**/*'
    - 'storage/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'spec/**/*'
    - 'config.ru'
    - 'Gemfile'
  TargetRubyVersion: 3.2
  SuggestExtensions: false

Style/Documentation:
  Enabled: false
Rails/I18nLocaleTexts:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
