services:
  app:
    build:
      dockerfile: Dockerfile.development
    stdin_open: true
    tty: true
    volumes:
      - ./:/app/
    ports:
      - 3000:3000
    command: bash -c "rm -rf /app/tmp/pids/server.pid &&
                      rails s -p 3000 -b 0.0.0.0"
    depends_on:
      - db
  sass:
    build:
      dockerfile: Dockerfile.development
    stdin_open: true
    tty: true
    volumes:
      - ./:/app/
    command: bash -c "bin/rails dartsass:watch"
    depends_on:
      - app
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgres/data
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
